### ISSUE TITLE
Can you provide the answers to the exercises?

### ISSUE THREAD

**Issue by gxx777** [hellman/ches2022wbc#1]
Hi，
Can you provide the answers to the exercises ? I may need some help from the answers.
Thanks!

**Comment by hellman** [comment]
Hi, you closed the issue, are solutions published somewhere? I will do it at some point soon. But the tutorials will be maintained in https://github.com/hellman/wboxkit

**Comment by gxx777** [comment]
Hi,

I have done it by myself. So I close the issue.I clone the project in order to code SM4 algorithm circuit to implment masking whitebox-cryptography scheme.Now,I have coded a Bitslice SM4 Program by Usuba.

Thanks!

**Comment by hellman** [comment]
Sounds cool! Let me know if you have any difficulties.
